name: Download and Release

on:
  workflow_dispatch:  # دستی اجرا کنی
  push:
    paths:
      - 'link.txt'

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run downloader
        run: python download.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.run_number }}
          name: Auto Release ${{ github.run_number }}
          files: downloads/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
